import About from './about'
import Home from './home'
import Contact from './contact'
import ProductDetails from './product-details'
import Shop from './shop'
import Account from './account'
import { Authentication } from './authentication'
import CartPage  from './cart'
import CheckoutPage  from './checkout'
import PaymentPage from './payment'
export {About, Home, Contact, ProductDetails, Shop, Authentication, Account, CartPage, CheckoutPage, PaymentPage}